### ISSUE TITLE
Will not load images using background url()

### ISSUE THREAD

**Issue by lmuzquiz** [petrpacas/webpack-bootstrap-4-setup#1]
I think there is a problem when loading images using url().

for example, If on the head of index.html you try to use something like: 

```
<style>
.container {
      background-image: url(assets/image.png);
    }`
<style>

```

or if you try within the html body something like:

`<div style="height: 100px; background:url(assets/image.png)"></div>
`

then **it will not load image.png**

Of course you have to **try it with a different image than hello.png** cause otherwise it will load. (since you are calling that hello.png image from index.html on a different tag). 

An ugly work around is to include:` require('./assets/image.png')` on main.js and then the images will load. But there's got to be a much better and elegant solution.

**Comment by petrpacas** [comment]
I don't actually use this setup much, so I didn't run into it yet, thanks for letting me know. I'll try to look into this, but if anyone beats me to it, I'd be more than happy :-)
